version: '3'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    restart: always
    ports: 
      - 3000:3000
    working_dir: /home/node/app
    expose: 
      - 3000
    command: "npm run start"
    networks:
      - instrumentenplatform

networks:
  instrumentenplatform:
    external: true