version: '3'

services:
  proxy:
    image: node:14.16.0
    user: node
    ports: 
      - 3000:3000
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose: 
      - 3000
    command: "npm run start"